services:
    orchestrator:
      build: ./orchestrator
      ports: 
        - "80:80"
      environment: 
        PORT: 80
        REDIS_PASSWORD: ${REDIS_PASSWORD}
        REDIS_HOST: ${REDIS_HOST}
        SERVER_USER_URL: "http://user:4001"
        SERVER_APP_URL: "http://app:4002"
        NODE_ENV: "production"
    app:
        build: ./services/app
        ports:
            - "4002:4002"
        environment:
            DATABASE_URL: ${DATABASE_URL}
            NODE_ENV: "production"
    user:
        build: ./services/users
        ports:
            - "4001:4001"
        environment:
          MONGODB_URL: ${MONGODB_URL}
          NODE_ENV: "production"